// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/lsm.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddedFile is the manifest metadata for one referenced SSTable.
type AddedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          uint32                 `protobuf:"varint,1,opt,name=tier,proto3" json:"tier,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	MinKey        []byte                 `protobuf:"bytes,3,opt,name=min_key,json=minKey,proto3" json:"min_key,omitempty"`
	MaxKey        []byte                 `protobuf:"bytes,4,opt,name=max_key,json=maxKey,proto3" json:"max_key,omitempty"`
	Count         uint64                 `protobuf:"varint,5,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddedFile) Reset() {
	*x = AddedFile{}
	mi := &file_proto_lsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedFile) ProtoMessage() {}

func (x *AddedFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedFile.ProtoReflect.Descriptor instead.
func (*AddedFile) Descriptor() ([]byte, []int) {
	return file_proto_lsm_proto_rawDescGZIP(), []int{0}
}

func (x *AddedFile) GetTier() uint32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *AddedFile) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *AddedFile) GetMinKey() []byte {
	if x != nil {
		return x.MinKey
	}
	return nil
}

func (x *AddedFile) GetMaxKey() []byte {
	if x != nil {
		return x.MaxKey
	}
	return nil
}

func (x *AddedFile) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// VersionEdit is one atomic manifest operation. A flush or compaction records
// every added file, every removed file, and its durability watermark in this
// single protobuf payload before physical framing.
type VersionEdit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddedFiles    []*AddedFile           `protobuf:"bytes,1,rep,name=added_files,json=addedFiles,proto3" json:"added_files,omitempty"`
	RemovedFiles  []string               `protobuf:"bytes,2,rep,name=removed_files,json=removedFiles,proto3" json:"removed_files,omitempty"`
	FlushedIndex  uint64                 `protobuf:"varint,3,opt,name=flushed_index,json=flushedIndex,proto3" json:"flushed_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionEdit) Reset() {
	*x = VersionEdit{}
	mi := &file_proto_lsm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionEdit) ProtoMessage() {}

func (x *VersionEdit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lsm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionEdit.ProtoReflect.Descriptor instead.
func (*VersionEdit) Descriptor() ([]byte, []int) {
	return file_proto_lsm_proto_rawDescGZIP(), []int{1}
}

func (x *VersionEdit) GetAddedFiles() []*AddedFile {
	if x != nil {
		return x.AddedFiles
	}
	return nil
}

func (x *VersionEdit) GetRemovedFiles() []string {
	if x != nil {
		return x.RemovedFiles
	}
	return nil
}

func (x *VersionEdit) GetFlushedIndex() uint64 {
	if x != nil {
		return x.FlushedIndex
	}
	return 0
}

var File_proto_lsm_proto protoreflect.FileDescriptor

const file_proto_lsm_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/lsm.proto\x12\n" +
	"miniquorum\"{\n" +
	"\tAddedFile\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\rR\x04tier\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x17\n" +
	"\amin_key\x18\x03 \x01(\fR\x06minKey\x12\x17\n" +
	"\amax_key\x18\x04 \x01(\fR\x06maxKey\x12\x14\n" +
	"\x05count\x18\x05 \x01(\x04R\x05count\"\x8f\x01\n" +
	"\vVersionEdit\x126\n" +
	"\vadded_files\x18\x01 \x03(\v2\x15.miniquorum.AddedFileR\n" +
	"addedFiles\x12#\n" +
	"\rremoved_files\x18\x02 \x03(\tR\fremovedFiles\x12#\n" +
	"\rflushed_index\x18\x03 \x01(\x04R\fflushedIndexB\x19Z\x17miniquorum/proto;raftpbb\x06proto3"

var (
	file_proto_lsm_proto_rawDescOnce sync.Once
	file_proto_lsm_proto_rawDescData []byte
)

func file_proto_lsm_proto_rawDescGZIP() []byte {
	file_proto_lsm_proto_rawDescOnce.Do(func() {
		file_proto_lsm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lsm_proto_rawDesc), len(file_proto_lsm_proto_rawDesc)))
	})
	return file_proto_lsm_proto_rawDescData
}

var file_proto_lsm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lsm_proto_goTypes = []any{
	(*AddedFile)(nil),   // 0: miniquorum.AddedFile
	(*VersionEdit)(nil), // 1: miniquorum.VersionEdit
}
var file_proto_lsm_proto_depIdxs = []int32{
	0, // 0: miniquorum.VersionEdit.added_files:type_name -> miniquorum.AddedFile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_lsm_proto_init() }
func file_proto_lsm_proto_init() {
	if File_proto_lsm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lsm_proto_rawDesc), len(file_proto_lsm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_lsm_proto_goTypes,
		DependencyIndexes: file_proto_lsm_proto_depIdxs,
		MessageInfos:      file_proto_lsm_proto_msgTypes,
	}.Build()
	File_proto_lsm_proto = out.File
	file_proto_lsm_proto_goTypes = nil
	file_proto_lsm_proto_depIdxs = nil
}
