// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	EntryType_NORMAL                 EntryType = 1
	EntryType_NOOP                   EntryType = 2
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "NORMAL",
		2: "NOOP",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED": 0,
		"NORMAL":                 1,
		"NOOP":                   2,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_raft_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_proto_raft_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	From  uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To    uint64                 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Term  uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Message_RequestVote
	//	*Message_RequestVoteResp
	//	*Message_AppendEntries
	//	*Message_AppendEntriesResp
	//	*Message_InstallSnapshot
	//	*Message_InstallSnapshotResp
	Body          isMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Message) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Message) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Message) GetBody() isMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message) GetRequestVote() *RequestVoteReq {
	if x != nil {
		if x, ok := x.Body.(*Message_RequestVote); ok {
			return x.RequestVote
		}
	}
	return nil
}

func (x *Message) GetRequestVoteResp() *RequestVoteResp {
	if x != nil {
		if x, ok := x.Body.(*Message_RequestVoteResp); ok {
			return x.RequestVoteResp
		}
	}
	return nil
}

func (x *Message) GetAppendEntries() *AppendEntriesReq {
	if x != nil {
		if x, ok := x.Body.(*Message_AppendEntries); ok {
			return x.AppendEntries
		}
	}
	return nil
}

func (x *Message) GetAppendEntriesResp() *AppendEntriesResp {
	if x != nil {
		if x, ok := x.Body.(*Message_AppendEntriesResp); ok {
			return x.AppendEntriesResp
		}
	}
	return nil
}

func (x *Message) GetInstallSnapshot() *InstallSnapshotChunk {
	if x != nil {
		if x, ok := x.Body.(*Message_InstallSnapshot); ok {
			return x.InstallSnapshot
		}
	}
	return nil
}

func (x *Message) GetInstallSnapshotResp() *InstallSnapshotResp {
	if x != nil {
		if x, ok := x.Body.(*Message_InstallSnapshotResp); ok {
			return x.InstallSnapshotResp
		}
	}
	return nil
}

type isMessage_Body interface {
	isMessage_Body()
}

type Message_RequestVote struct {
	RequestVote *RequestVoteReq `protobuf:"bytes,4,opt,name=request_vote,json=requestVote,proto3,oneof"`
}

type Message_RequestVoteResp struct {
	RequestVoteResp *RequestVoteResp `protobuf:"bytes,5,opt,name=request_vote_resp,json=requestVoteResp,proto3,oneof"`
}

type Message_AppendEntries struct {
	AppendEntries *AppendEntriesReq `protobuf:"bytes,6,opt,name=append_entries,json=appendEntries,proto3,oneof"`
}

type Message_AppendEntriesResp struct {
	AppendEntriesResp *AppendEntriesResp `protobuf:"bytes,7,opt,name=append_entries_resp,json=appendEntriesResp,proto3,oneof"`
}

type Message_InstallSnapshot struct {
	InstallSnapshot *InstallSnapshotChunk `protobuf:"bytes,8,opt,name=install_snapshot,json=installSnapshot,proto3,oneof"`
}

type Message_InstallSnapshotResp struct {
	InstallSnapshotResp *InstallSnapshotResp `protobuf:"bytes,9,opt,name=install_snapshot_resp,json=installSnapshotResp,proto3,oneof"`
}

func (*Message_RequestVote) isMessage_Body() {}

func (*Message_RequestVoteResp) isMessage_Body() {}

func (*Message_AppendEntries) isMessage_Body() {}

func (*Message_AppendEntriesResp) isMessage_Body() {}

func (*Message_InstallSnapshot) isMessage_Body() {}

func (*Message_InstallSnapshotResp) isMessage_Body() {}

type RequestVoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   uint64                 `protobuf:"varint,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm   uint64                 `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReq) Reset() {
	*x = RequestVoteReq{}
	mi := &file_proto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReq) ProtoMessage() {}

func (x *RequestVoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReq.ProtoReflect.Descriptor instead.
func (*RequestVoteReq) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{1}
}

func (x *RequestVoteReq) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReq) GetCandidateId() uint64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVoteReq) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteReq) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResp) Reset() {
	*x = RequestVoteResp{}
	mi := &file_proto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResp) ProtoMessage() {}

func (x *RequestVoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResp.ProtoReflect.Descriptor instead.
func (*RequestVoteResp) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RequestVoteResp) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResp) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type AppendEntriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogIndex  uint64                 `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm   uint64                 `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  uint64                 `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesReq) Reset() {
	*x = AppendEntriesReq{}
	mi := &file_proto_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesReq) ProtoMessage() {}

func (x *AppendEntriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesReq.ProtoReflect.Descriptor instead.
func (*AppendEntriesReq) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntriesReq) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesReq) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntriesReq) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesReq) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesReq) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesReq) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResp) Reset() {
	*x = AppendEntriesResp{}
	mi := &file_proto_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResp) ProtoMessage() {}

func (x *AppendEntriesResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResp.ProtoReflect.Descriptor instead.
func (*AppendEntriesResp) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{4}
}

func (x *AppendEntriesResp) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InstallSnapshotChunk struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Term              uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId          uint64                 `protobuf:"varint,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	LastIncludedIndex uint64                 `protobuf:"varint,3,opt,name=lastIncludedIndex,proto3" json:"lastIncludedIndex,omitempty"`
	LastIncludedTerm  uint64                 `protobuf:"varint,4,opt,name=lastIncludedTerm,proto3" json:"lastIncludedTerm,omitempty"`
	Offset            uint64                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Data              []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Done              bool                   `protobuf:"varint,7,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallSnapshotChunk) Reset() {
	*x = InstallSnapshotChunk{}
	mi := &file_proto_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotChunk) ProtoMessage() {}

func (x *InstallSnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotChunk.ProtoReflect.Descriptor instead.
func (*InstallSnapshotChunk) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{5}
}

func (x *InstallSnapshotChunk) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotChunk) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InstallSnapshotChunk) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *InstallSnapshotChunk) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *InstallSnapshotChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *InstallSnapshotChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InstallSnapshotChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type InstallSnapshotResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotResp) Reset() {
	*x = InstallSnapshotResp{}
	mi := &file_proto_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotResp) ProtoMessage() {}

func (x *InstallSnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotResp.ProtoReflect.Descriptor instead.
func (*InstallSnapshotResp) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{6}
}

func (x *InstallSnapshotResp) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Term          uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Type          EntryType              `protobuf:"varint,3,opt,name=type,proto3,enum=miniquorum.EntryType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{7}
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResp) Reset() {
	*x = SendResp{}
	mi := &file_proto_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResp) ProtoMessage() {}

func (x *SendResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResp.ProtoReflect.Descriptor instead.
func (*SendResp) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{8}
}

var File_proto_raft_proto protoreflect.FileDescriptor

const file_proto_raft_proto_rawDesc = "" +
	"\n" +
	"\x10proto/raft.proto\x12\n" +
	"miniquorum\"\x93\x04\n" +
	"\aMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x04R\x02to\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12?\n" +
	"\frequest_vote\x18\x04 \x01(\v2\x1a.miniquorum.RequestVoteReqH\x00R\vrequestVote\x12I\n" +
	"\x11request_vote_resp\x18\x05 \x01(\v2\x1b.miniquorum.RequestVoteRespH\x00R\x0frequestVoteResp\x12E\n" +
	"\x0eappend_entries\x18\x06 \x01(\v2\x1c.miniquorum.AppendEntriesReqH\x00R\rappendEntries\x12O\n" +
	"\x13append_entries_resp\x18\a \x01(\v2\x1d.miniquorum.AppendEntriesRespH\x00R\x11appendEntriesResp\x12M\n" +
	"\x10install_snapshot\x18\b \x01(\v2 .miniquorum.InstallSnapshotChunkH\x00R\x0finstallSnapshot\x12U\n" +
	"\x15install_snapshot_resp\x18\t \x01(\v2\x1f.miniquorum.InstallSnapshotRespH\x00R\x13installSnapshotRespB\x06\n" +
	"\x04body\"\x8c\x01\n" +
	"\x0eRequestVoteReq\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12 \n" +
	"\vcandidateId\x18\x02 \x01(\x04R\vcandidateId\x12\"\n" +
	"\flastLogIndex\x18\x03 \x01(\x04R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x04 \x01(\x04R\vlastLogTerm\"G\n" +
	"\x0fRequestVoteResp\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12 \n" +
	"\vvoteGranted\x18\x02 \x01(\bR\vvoteGranted\"\xd9\x01\n" +
	"\x10AppendEntriesReq\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x02 \x01(\x04R\bleaderId\x12\"\n" +
	"\fprevLogIndex\x18\x03 \x01(\x04R\fprevLogIndex\x12 \n" +
	"\vprevLogTerm\x18\x04 \x01(\x04R\vprevLogTerm\x12+\n" +
	"\aentries\x18\x05 \x03(\v2\x11.miniquorum.EntryR\aentries\x12\"\n" +
	"\fleaderCommit\x18\x06 \x01(\x04R\fleaderCommit\"A\n" +
	"\x11AppendEntriesResp\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\xe0\x01\n" +
	"\x14InstallSnapshotChunk\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x02 \x01(\x04R\bleaderId\x12,\n" +
	"\x11lastIncludedIndex\x18\x03 \x01(\x04R\x11lastIncludedIndex\x12*\n" +
	"\x10lastIncludedTerm\x18\x04 \x01(\x04R\x10lastIncludedTerm\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\a \x01(\bR\x04done\")\n" +
	"\x13InstallSnapshotResp\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\"p\n" +
	"\x05Entry\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.miniquorum.EntryTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\n" +
	"\n" +
	"\bSendResp*=\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\b\n" +
	"\x04NOOP\x10\x0229\n" +
	"\x04Raft\x121\n" +
	"\x04Send\x12\x13.miniquorum.Message\x1a\x14.miniquorum.SendRespB\x19Z\x17miniquorum/proto;raftpbb\x06proto3"

var (
	file_proto_raft_proto_rawDescOnce sync.Once
	file_proto_raft_proto_rawDescData []byte
)

func file_proto_raft_proto_rawDescGZIP() []byte {
	file_proto_raft_proto_rawDescOnce.Do(func() {
		file_proto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_raft_proto_rawDesc), len(file_proto_raft_proto_rawDesc)))
	})
	return file_proto_raft_proto_rawDescData
}

var file_proto_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_raft_proto_goTypes = []any{
	(EntryType)(0),               // 0: miniquorum.EntryType
	(*Message)(nil),              // 1: miniquorum.Message
	(*RequestVoteReq)(nil),       // 2: miniquorum.RequestVoteReq
	(*RequestVoteResp)(nil),      // 3: miniquorum.RequestVoteResp
	(*AppendEntriesReq)(nil),     // 4: miniquorum.AppendEntriesReq
	(*AppendEntriesResp)(nil),    // 5: miniquorum.AppendEntriesResp
	(*InstallSnapshotChunk)(nil), // 6: miniquorum.InstallSnapshotChunk
	(*InstallSnapshotResp)(nil),  // 7: miniquorum.InstallSnapshotResp
	(*Entry)(nil),                // 8: miniquorum.Entry
	(*SendResp)(nil),             // 9: miniquorum.SendResp
}
var file_proto_raft_proto_depIdxs = []int32{
	2, // 0: miniquorum.Message.request_vote:type_name -> miniquorum.RequestVoteReq
	3, // 1: miniquorum.Message.request_vote_resp:type_name -> miniquorum.RequestVoteResp
	4, // 2: miniquorum.Message.append_entries:type_name -> miniquorum.AppendEntriesReq
	5, // 3: miniquorum.Message.append_entries_resp:type_name -> miniquorum.AppendEntriesResp
	6, // 4: miniquorum.Message.install_snapshot:type_name -> miniquorum.InstallSnapshotChunk
	7, // 5: miniquorum.Message.install_snapshot_resp:type_name -> miniquorum.InstallSnapshotResp
	8, // 6: miniquorum.AppendEntriesReq.entries:type_name -> miniquorum.Entry
	0, // 7: miniquorum.Entry.type:type_name -> miniquorum.EntryType
	1, // 8: miniquorum.Raft.Send:input_type -> miniquorum.Message
	9, // 9: miniquorum.Raft.Send:output_type -> miniquorum.SendResp
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_raft_proto_init() }
func file_proto_raft_proto_init() {
	if File_proto_raft_proto != nil {
		return
	}
	file_proto_raft_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_RequestVote)(nil),
		(*Message_RequestVoteResp)(nil),
		(*Message_AppendEntries)(nil),
		(*Message_AppendEntriesResp)(nil),
		(*Message_InstallSnapshot)(nil),
		(*Message_InstallSnapshotResp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_raft_proto_rawDesc), len(file_proto_raft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_raft_proto_goTypes,
		DependencyIndexes: file_proto_raft_proto_depIdxs,
		EnumInfos:         file_proto_raft_proto_enumTypes,
		MessageInfos:      file_proto_raft_proto_msgTypes,
	}.Build()
	File_proto_raft_proto = out.File
	file_proto_raft_proto_goTypes = nil
	file_proto_raft_proto_depIdxs = nil
}
